source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCDownload_Example' do
  pod 'GCDMulticastDelegate'
  pod 'MCBase'
  pod 'MCDownload', path: '../'
  pod 'SDWebImage'
end
